### ISSUE TITLE
Refactor the way scoresheet data is passed into the template

### ISSUE THREAD

**Issue by prphntm63** [CIA-Homebrew/BJCP-Scoresheet#93]
Currently, scoresheet data is passed into the scoresheet pug template and "Object-ified" by using a hideous bit of logic:

[`var scoresheet = '#{scoresheet}' !== '' ? JSON.parse('!{JSON.stringify(scoresheet).replace(/\\\"/g, "\\\\\"").replace(/\'/g, "\\\'")}') : null;`](https://github.com/CIA-Homebrew/BJCP-Scoresheet/blob/450171e3e391075c561db5b30b99a804ea37de60/views/scoresheet.pug#L1503)

This is not ideal, and breaks at just about every chance it gets. 

We need a more robust method to past the scoresheet JSON data to the template to be populated in after the page loads. This can be done by either
- Creating a more robust data sanitation method to pass this data with the initial HTML through pug
- Creating a `fetchScoresheetDataById` endpoint and adding a fetch POST call on the front end (most ideal)

**Comment by PH-Lazurous** [comment]
Why are we re-declaring that anyways? The scoresheet variable is set from the controller to pug for render already.

**Comment by prphntm63** [comment]
Yes, but it is not passed into the script as a variable. The "scoresheet" variable passed into the template only exists at pug runtime.

**Comment by PH-Lazurous** [comment]
But do we need "it" as a variable? Could we not leverage the form.serialize() method to capture a snapshot of the form data after initial population, then hold that in a variable. Then we don't have to make a needless call to the backend for data we already have available at runtime, and still have a variable without doing anything squirrely. it would require quite a bit of value plugs into the scoresheet form but nothing crazy. I guess the biggest question beyond that is does it get rid of our quote error we are having to begin with because we aren't shifting things around using JSON.strigify?! 

Thinking out loud here, and I haven't tested any of these thoughts,  I just think the additional call to the backend for data we already have is redundant and unneeded.

**Comment by prphntm63** [comment]
> Could we not leverage the form.serialize() method to capture a snapshot of the form data after initial population, then hold that in a variable.

That's the problem - this is happening one step before that, where the fields are populated in the first place

Ideally (recapping what we disucssed on discord) we should only have hidden `id` field populated from the template, then set up a an `fetchScoresheetDataById` endpoint to return the scoresheet, user, and flight data, then fetch and populate it after page load.
